const routes = {
    '/': '首页',
    '/dashboard': '控制台',
    '/components': 'Components',
    '/charts': 'Charts',
    '/components/buttons': 'Buttons',
    '/components/social-buttons': 'Buttons',
    '/components/cards': 'Cards',
    '/components/forms': 'Forms',
    '/components/modals': 'Modals',
    '/components/switches': 'Switches',
    '/components/tables': 'Tables',
    '/components/tabs': 'Tabs',
    '/components/svgs': 'Svgs',
    '/icons': 'Icons',
    '/icons/font-awesome': 'Font Awesome',
    '/icons/simple-line-icons': 'Simple Line Icons',
    '/widgets': 'Widgets',
    '/settings': '设置',
    '/settings/banks': '银行列表',
    '/orders':'订单管理',
    '/orders/all':'订单列表',
    '/orderdetail':'订单详情'
};
export default routes;
